version: 2
workflows:
  version: 2
  testing:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/php:7.1-fpm-jessie-browsers

    working_directory: ~/repo
    steps:
      - run:
          name: "Install composer"
          command: |
            LAST_PWD=${PWD}
            cd /tmp/
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === '93b54496392c062774670ac18b134c3b3a95e5a5e5c8f1a9f115f203b75bf9a129d5daa8ba6a13e2cc8a1da0806388a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
            sudo mv ./composer.phar /usr/local/bin/composer
            sudo chmod +x /usr/local/bin/composer
            cd ${LAST_PWD}

      - checkout

      - restore_cache:
          keys:
          - composer-dev-v1-{{ checksum "composer.json" }}

      - run: composer install --classmap-authoritative

      - save_cache:
          paths:
            - ./vendor
          key: composer-dev-v1-{{ checksum "composer.json" }}

      - run: if [ -f vendor/bin/phpunit ]; then vendor/bin/phpunit; fi
      - run: if [ -f vendor/bin/pharmacist ]; then vendor/bin/pharmacist; fi
      - run: if [ -f vendor/bin/phpstan ]; then php -d memory_limit=4G vendor/bin/phpstan analyse -l 0 src $(if [ -f phpstan.neon ]; then echo "-c phpstan.neon"; fi); fi